---
title: "Demonstration Datasets for Hybrid Experimental Designs"
output:
  html_document:
    toc: true
    toc_depth: 1 
---

#### On this page we provide example datasets, analysis code in SAS and R, and outputs, for the three kinds of hybrid experimental designs considered in this recent paper:

> Nahum-Shani, I., Dziak, J. J., Venera, H., Spring, B., & Dempsey W. (2023). [Design of Experiments with Sequential Randomizations at Multiple Time Scales: The Hybrid Experimental Design](https://link.springer.com/article/10.3758/s13428-023-02119-z). *Behavior Research Methods*, [doi:10.3758/s13428-023-02119-z](https://doi.org/10.3758/s13428-023-02119-z). 

#### Each example is based on a hypothetical study to answer questions which inform the design of weight loss interventions integrating multiple components.  More details on the motivation and interpretation for each example is given in Nahum-Shani et al (2023).

# Hybrid Factorial-SMART

In the example hybrid factorial-SMART, the hypothetical intervention being considered would begin by providing a mobile app (*App*) and/or weekly coaching (*Coaching*).  Participants who show early signs of nonresponse after 2 weeks would be offered meal replacement (*Meal*).  The research questions are 

- To achieve maximum weight loss at month 6, is it better to initially offer *App* and/or *Coaching*?

- For nonresponders, is it beneficial (in terms of weight loss at month 6) to add *Meal*?

The first question is addressed by a 2*2 factorial randomization in the initial randomization stage.  The second question is addressed by a second-stage random assignment of nonresponders to 'stay the course' or to additionally add meal replacement. The resulting design is a hybrid factorial-SMART.


### Downloads

- [Simulated Data](Simulated_Data_Hybrid_Factorial_SMART.csv)

- [Analysis Code for SAS](Analyze_Simulated_Data_Hybrid_Factorial_SMART.sas)

- [Sample Output from SAS](factorial-smart-results.pdf)

- [Analysis Code for R](Analyze_Simulated_Data_Hybrid_Factorial_SMART.R)

### Sample Output from R

```
Call:
geeglm(formula = model_formula, data = data_for_analysis, weights = replicate_weight, 
    id = ID, corstr = "independence")

 Coefficients:
                      Estimate  Std.err    Wald Pr(>|W|)    
(Intercept)            2.22928  0.11300 389.197  < 2e-16 ***
is_female              0.09250  0.11293   0.671  0.41273    
baseline_bmi_centered -0.06860  0.03363   4.161  0.04137 *  
app                    0.11394  0.10753   1.123  0.28930    
coaching               0.71485  0.10740  44.304 2.81e-11 ***
meal                   0.92702  0.08558 117.322  < 2e-16 ***
app:coaching           0.10818  0.10749   1.013  0.31424    
app:meal              -0.01785  0.08570   0.043  0.83501    
coaching:meal          0.27742  0.08524  10.592  0.00114 ** 
app:coaching:meal      0.11796  0.08547   1.905  0.16754    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation structure = independence 
Estimated Scale Parameters:

            Estimate Std.err
(Intercept)    4.902  0.3208
Number of clusters:   400  Maximum cluster size: 2 
```
 
# Hybrid Factorial-MRT
         
In the example hybrid factorial-MRT,  the intervention being considered the initial intervention would include a supportive app that can be used to record dietary intake, and it might include coaching sessions (*Coaching*) and/or meal replacement (*Meal*). The researcher wants to determine whether either or both of these factors are sufficiently effective to be worth including, in terms of the final goal or 'distal outcome' of weight loss after six months. Also, during the course of the study, a mobile phone text prompt or push notification (*Prompt*) might be given on some days at noon, reminding the participant to monitor food intake.  The researcher wants to know whether this prompt improves the short-term goal or 'proximal outcome' of dietary self-monitoring that day. Thus there are separate questions, requiring separate analyses, for the  distal and proximal  outcomes. 

### Downloads
- [Simulated Occasion-Level Data](Simulated_Data_Hybrid_Factorial_MRT_occasion_level.csv)

- [Simulated Person-Level Data](Simulated_Data_Hybrid_Factorial_MRT_person_level.csv)

- [Analysis Code for R](Analyze_Simulated_Data_Hybrid_Factorial_MRT.R)

- [Analysis Code for SAS](Analyze_Simulated_Data_Hybrid_Factorial_MRT.sas)

- [Sample Output from SAS](factorial-mrt-results.pdf) 

###  Sample Output from R
#### Distal:
```

Call:
lm(formula = final_kg_lost ~ is_female + baseline_bmi_centered + 
    coaching * meal, data = person_level)

Residuals:
   Min     1Q Median     3Q    Max 
-7.011 -1.682 -0.178  1.598  9.616 

Coefficients:
                      Estimate Std. Error t value Pr(>|t|)    
(Intercept)             2.5651     0.1344   19.08  < 2e-16 ***
is_female              -0.0289     0.1349   -0.21   0.8306    
baseline_bmi_centered  -0.1962     0.0389   -5.04  7.2e-07 ***
coaching                0.2053     0.1237    1.66   0.0978 .  
meal                    0.3308     0.1235    2.68   0.0077 ** 
coaching:meal           0.0330     0.1236    0.27   0.7897    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 2.47 on 394 degrees of freedom
Multiple R-squared:  0.0837,	Adjusted R-squared:  0.0721 
F-statistic:  7.2 on 5 and 394 DF,  p-value: 1.82e-06
```
#### Proximal:
```
Call:
geeglm(formula = proximal_outcome ~ is_female + baseline_bmi_centered + 
    A * coaching * meal, family = binomial(link = log), data = occasion_level, 
    id = ID, corstr = "independence")

 Coefficients:
                      Estimate  Std.err    Wald Pr(>|W|)    
(Intercept)           -0.50615  0.00526 9262.21  < 2e-16 ***
is_female              0.01383  0.00527    6.88   0.0087 ** 
baseline_bmi_centered -0.00451  0.00147    9.35   0.0022 ** 
A                      0.00707  0.00439    2.59   0.1073    
coaching               0.02136  0.00477   20.02  7.6e-06 ***
meal                   0.02523  0.00475   28.20  1.1e-07 ***
A:coaching             0.00927  0.00439    4.46   0.0346 *  
A:meal                 0.00287  0.00439    0.43   0.5131    
coaching:meal          0.00723  0.00476    2.31   0.1284    
A:coaching:meal        0.00632  0.00439    2.07   0.1501    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation structure = independence 
Estimated Scale Parameters:

            Estimate Std.err
(Intercept)        1 0.00285
Number of clusters:   400  Maximum cluster size: 84 
```


# Hybrid SMART-MRT

In the example hybrid SMART-MRT, the intervention being considered will begin with a mobile app to facilitate dietary self-monotoring, but the researcher wonders whether it might be beneficial to augment this by adding in-person coaching (*Coaching*), in terms of improving the distal outcome of six-month weight loss.  For nonresponders to the initial intervention, as assessed after 2 weeks, the researcher also wants to know whether it might be beneficial to add meal replacement (*Meal*), in terms of improving the distal outcome.  Also, the researcher wants to know whether it is beneficial on a given day to give a mobile text prompt (*Prompt*) encouraging self-monitoring, in terms of improving the proximal outcome of engagement with the self-monitoring app that day.


### Downloads
- [Simulated Occasion-Level Data](Simulated_Data_Hybrid_SMART_MRT_occasion_level.csv)

- [Simulated Person-Level Data](Simulated_Data_Hybrid_SMART_MRT_person_level.csv)

- [Analysis Code for SAS](Analyze_Simulated_Data_Hybrid_SMART_MRT.sas)

- [Sample Output from SAS](smart-mrt-results.pdf) 

- [Analysis Code for R](Analyze_Simulated_Data_Hybrid_SMART_MRT.R)

### Sample Output from R
#### Distal
```
Call:
geeglm(formula = final_kg_lost ~ is_female + baseline_bmi_centered + 
    coaching * meal, family = gaussian, data = person_level_data_for_analysis, 
    weights = replicate_weight, id = ID)

 Coefficients:
                      Estimate Std.err   Wald Pr(>|W|)    
(Intercept)             1.9457  0.1404 191.98   <2e-16 ***
is_female               0.2629  0.1403   3.51    0.061 .  
baseline_bmi_centered  -0.0366  0.0382   0.92    0.338    
coaching                0.6638  0.1276  27.07    2e-07 ***
meal                    0.1065  0.0907   1.38    0.240    
coaching:meal           0.0276  0.0908   0.09    0.761    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation structure = independence 
Estimated Scale Parameters:

            Estimate Std.err
(Intercept)     6.38   0.469
Number of clusters:   400  Maximum cluster size: 2 
```
#### Proximal
```
Call:
geeglm(formula = proximal_outcome ~ is_female + baseline_bmi_centered + 
    A * coaching * meal, family = binomial(link = log), data = occasion_level_data_for_analysis, 
    weights = replicate_weight, id = ID)

 Coefficients:
                       Estimate   Std.err    Wald Pr(>|W|)    
(Intercept)           -0.507430  0.005606 8194.45   <2e-16 ***
is_female              0.017033  0.005738    8.81    0.003 ** 
baseline_bmi_centered -0.000685  0.001514    0.20    0.651    
A                      0.007566  0.004641    2.66    0.103    
coaching               0.034190  0.004899   48.70    3e-12 ***
meal                   0.004951  0.003495    2.01    0.157    
A:coaching             0.010098  0.004641    4.73    0.030 *  
A:meal                 0.004567  0.003289    1.93    0.165    
coaching:meal          0.005349  0.003494    2.34    0.126    
A:coaching:meal       -0.000912  0.003290    0.08    0.782    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation structure = independence 
Estimated Scale Parameters:

            Estimate Std.err
(Intercept)        1 0.00283
Number of clusters:   400  Maximum cluster size: 168 
```

# Further Information

### What resources does this page provide?

This page provides links to simulated datasets and sample analysis code and output for three novel kinds of experimental designs for use in informing the development of multimodal adaptive interventions.

### How can an intervention scientist use the resources on this page?

This information may be useful in helping researchers to conceptualize the kinds of questions which each design can address, and in providing a partial template for the analysis of data from those designs.  

### See also:

- [A more advanced example analysis](https://github.com/d3center-isr/hybrid-experimental-design) for a hybrid SMART-MRT in which only nonresponders received the micro-randomized treatments, analyzed using a robust method which allows time-varying covariates.
 
- [Open-access preprint of the *Behavior Research Methods* article](https://arxiv.org/abs/2302.09046).
